### ISSUE TITLE
User Entity 네이밍 오류(테스트 코드 작성시)

### ISSUE THREAD

**Issue by gyuturn** [Nestsoft-Team/DunJi-BackEnd#18]
## 문제상황

현재 User class의 테이블 이름은 user이다

하지만 h2 database를 사용할때(테스트를 할때) h2에서 user는 예약어이기에 문제가 발생

## 해결방법
~~~
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "users")
public class User extends BaseTimeEntity implements UserDetails {
~~~
로 @Table(name="users")로 변경가능함

## 고려사항
- 테스트를 위해 바꾸는것이 맞는가?
- 다른분들의 의견도 궁금합니다!

**Comment by jeeheaG** [comment]
여기 나오는 대로 user의 예약어 해제 먼저 시도해 보는 건 어떨까요?
사용 전에 이걸 해제해서 어떤 영향이 있을지는 다시한번 찾아보면 좋을 것 같습니다!
https://icthuman.tistory.com/entry/Spring-JPA-H2-%EC%82%AC%EC%9A%A9%EC%8B%9C-GenerationTypeIDENTITY-%EC%98%A4%EB%A5%98

**Comment by gyuturn** [comment]
음 근데 제가 사용하는 library 가 "testImplementation 'com.h2database:h2'" 이걸 사용하고 있어 application.yml파일에서 url을 설정을 하지 못합니다.... 다른 레퍼런스를 찾아봤는데 저같은 오류는 table명을 변경하는걸로 되어 있더라구요...
@jeeheaG

**Comment by gyuturn** [comment]
@table(name="users")로 수정하는걸로 하겠습니다!
