### ISSUE TITLE
refresh token 로직 & 저장 위치

### ISSUE THREAD

**Issue by jeeheaG** [Nestsoft-Team/DunJi-BackEnd#5]
# 문제 상황
- 기존 결정 사항 : refresh token을 DB에 저장하고 그 저장위치 index값을 프론트에 암호화해서 보냄
- 이 방법이 그냥 refresh token 을 프론트에 보내는 거랑 같은 용도인 것 같음 (DB에 있는 refresh token값과 비교해서 토큰을 확인하는 용도)
- refresh token 대신 DB index값을 암호화해서 프론트에 보내려면 암호화하는 과정이 하나 더 추가되는 것
- 구현하려던 방법(프론트에 안보내고 DB에서만 꺼내쓰기)대로 하지 말라는 의견도 간혹 보임. 프론트에 안보내면 토큰의 존재 의미가 없다고 함.

#
# 대안
-  refresh token을 DB에도 저장하고, 프론트에도 보냄
- 결론적으로 제가 생각하는 로직
---
1. 로그인 시 access, refresh token발급 후 둘 다 쿠키로 프론트 저장 (httpOnly, Secure설정)
2. refresh token 는 DB에도 저장
3. 요청왔을 때 access token 만료 시 쿠키의 refresh token 유효기간 확인
4. 유효 시 해당 refresh token과 DB의 refresh token 일치 확인
4-1. 일치 시 access token 재발급 & 요청 처리
4-2. 불일치 시 요청 거절 (토큰이 탈취된 이후 실제 사용자가 로그아웃&재로그인하여 DB의 refresh token이 재발급된 것으로 간주)

5. 로그아웃 시 DB의 refresh token 삭제

---

#
### 논의중..
정답이 있는 문제는 아닌 것 같으니 편하게 의견 주시면 감사하겠습니다!

**Comment by gyuturn** [comment]
<img width="776" alt="스크린샷 2023-01-04 오전 10 05 39" src="https://user-images.githubusercontent.com/87477702/210465991-98d66337-e1e2-4810-a52c-94a249468261.png">

혹시 refresh를 DB에 저장하지 않는것은 어떤가요?

해당 이유

1. 저희가 웹앱이기에 결론적으론 사용자입장에서는 해당 페이지 url을 알 방법이 없는것으로 알 고 있습니다.(확실 x)
2. accesstoken은 암호화하지 않고 쿠키에 저장
3. refresh token은 암호화하여 쿠키에저장

해당 방식으로 사용하게 되면 accesstoken은 암호화하지 않아 인증처리를 빠르게 할 수 있습니다.
나아가 refresh를 DB에 저장하지 않기에 서버를 stateless하게 운영할 수 있습니다.

개인적으로 refresh를 DB에 저장하면 결국 session을 사용하는것과 다를게 없어지며, 오히려 안정적인 세션을 사용하는것이 더 좋다는 의견입니다!

**Comment by gyuturn** [comment]
https://velog.io/@ohzzi/Access-Token%EA%B3%BC-Refresh-Token%EC%9D%84-%EC%96%B4%EB%94%94%EC%97%90-%EC%A0%80%EC%9E%A5%ED%95%B4%EC%95%BC-%ED%95%A0%EA%B9%8C

혹은 해당방식도 있습니다
1. access 토큰은 자바스크립트 private 변수로 저장
2. refresh token은 쿠키에 저장

정확한 답은 없는것 같긴합니다

**Comment by jeeheaG** [comment]
여러 방법 말씀감사합니다! 저도 말씀하신 부분들 모두 동의해서 찾아볼수록 굳이 DB에 저장하지 않아도 될 것 같다는 생각이 듭니다. 

#
### 1. DB 저장없이 쿠키 사용, 프론트에서 private변수 저장
js의 private변수에 저장하는 방식은 프론트에서 토큰을 보관하는 방법인 것 같으니 프론트분들께 말씀드리는 걸로 하고, 토큰을 주고받을 때에는 저희 아마 HTTPS도 사용할 테니까 httponly, secure 설정이 된 쿠키에 저장하면 괜찮을 것 같아요.

### 2. refresh token 이중암호화가 필요한 부분일까요?
이미 한번 암호화된 JWT토큰 자체를 한번 더 암호화하는 건 의미가 없다는 생각이 드는데 그 이유는 아래와 같습니다.
- 그냥 jwt토큰을 사용할 때와 똑같음 : 서버측에서 jwt를 한번 더 암호화한 값을 프론트에 전달하고 프론트가 그 값을 서버로 보내서 사용할텐데, 공격자가 암호화된 값을 탈취해서 그대로 서버로 보내오면 뚫리게 됨
- jwt를 복호화할 수 없도록 한번 더 암호화하여 보안성을 높이는 용도라면 암호화를 한번 더 하기보다는, jwt암호화 과정에서 사용되는 시크릿키 등의 부분을 신경써서 jwt토큰 자체의 보안성을 높이는 방향을 먼저 고려해야한다고 생각함

의견 남겨주시면 감사하겠습니다!

+) 추가로 질문이 있는데 웹앱이라 사용자가 url을 알 수 없다는 말씀은 사용자가 굳이 토큰이 담긴 쿠키를 열어보기 어려우니 쿠키를 사용해도 괜찮을 거라는 의미일까요?

#
돌고 돌아서 쿠키로 돌아오고 있는 것 같네요 ㅎ..

**Comment by gyuturn** [comment]
저도 JWT를 한번더 암호화하는것은 의미가 없다고 생각합니다. 지혜님이 적으신것 처럼 결국 서버로 보내게되면 의미가 없다고 생각합니다.

## 그러면 결론적으로는
accesstoken: js private 변수로 저장(React SPA라서 accesstoken 보관이가능합니다.)
refreshToken: 쿠키저장

## 이로얻는 이점
- 서버는 StateLess 상태 유지 가능(이게 가장 중요하다고 생각합니다. JWT를 사용하는게 StateLess하기 위해서니까요)
- DB에 저장하지 않기때문에 1회성값일 수 있는 토큰을 관리하지 않아두됨

#### 추가질문 답변
네 저도 웹앱을 다루어본적은 없는데 결국 사용자는 어플을 사용하는것이고 어플은 url을 볼 수 없는것으로 알 고 있습니다. 그렇기에 저희가 웹앱이어도 웹으로 접근할 수 있는 방법은 관리자가 아니면 알지 못한다고 생각했습니다.(제대로 찾아보지 않아서 아닐 수 도 있습니다.) 그렇기에 쿠키를 사용해도 무관하다고 생각됩니다.!

**Comment by jeeheaG** [comment]
네 정리해주신 내용 모두 동의합니다! 질문 답변도 감사합니다. 

다만 지금 구현할 시간이 부족한 상황이니 프론트측과 상의가 필요한 js private 변수 사용은 미뤄두고
access token, refresh token 모두 일단 쿠키 저장으로 구현하겠습니다.
나중에 여유가 되면 보안성 높이는 방향으로 변경하면 좋을 것 같습니다.

마지막으로 이제 DB에 토큰을 저장하지 않으니까 
refresh token 을 1회용으로 사용하는 RTR로직 적용도 제가 개발하면서 해보겠습니다! 
(시간상 무리라고 생각되면 제외 예정)

[최종 로직]
1. access, refresh token 모두 쿠키 저장
2. httpOnly, Secure설정함
3. RTR 적용 긍정적 고려

** DB에 토큰 저장하지 않음 - jwt의 의미 살리고 서버 stateless 운영
